package gofive.models.bl.consts;

/**
 * 行业分类。
 *
 * Created by coral on 2016/3/20 0020.
 */
public enum Industry {
    WEISHENG, PIFALINGSHOU, ZHUSUCANYIN, DIANLIRELI, JIAOYU, NONGLINMUYU, JINRONG, JIANZHU, JIAOTONGYUNSHU, CAIKUANG,
    WENHUATIYUYULE, SHUILIHUANJING, ZONGHE, FANGDICHAN, ZULINGSHANGWUFUWU, ZHIZAO, XINXICHUANSHU, KEXUEYANJIUJISHU
}
